In [1]:
import pandas as pd

In [2]:
data = "./data/TP_SIDERs_coor.csv"
df = pd.read_csv(data, sep=",", header=0)
df.head()

,qseqid,sseqid,pident,length,qstart,qend,sstart,send,evalue,bitscore,qlen,slen,sstrand,sseq
0,1-112979r,LinJ.01,99.614,259,1,259,114017,113760,5.440000e-135,472.0,259,278267,minus,GGGGTGAGGCGGCGGCGCACAGACACACACACACACACACACACGC...
1,1-129494r,LinJ.01,100.000,447,1,447,130577,130131,0.000000e+00,826.0,447,278267,minus,TGATGACGGGGCGGCGGCGCACAGACACACACACACACACACACAC...
2,1-136422d,LinJ.01,100.000,461,1,461,137458,137918,0.000000e+00,852.0,461,278267,plus,TGACGACGGGGTGGGGCGGCGGCGCACAGACACACACACACACACA...
3,1-204526d,LinJ.01,100.000,432,1,432,205558,205989,0.000000e+00,798.0,432,278267,plus,GATGACGGGGTGGGGCGGCGGCGCACACACACACACGCACACACCT...
4,1-24471d,LinJ.01,100.000,660,1,660,24099,24758,0.000000e+00,1219.0,660,278267,plus,GGCGGGGGAGGCGGGGGGCACGCACCTCCATGCGTGGCATCCCAGG...

In [7]:
(df['sstart'] > df['send']).sum()

787