Author: Ronny F. Pacheco Date: OCt 2024
Copyright: Â© 2024 Ronny Pacheco License: MIT License

---

MIT License

Copyright (c) 2024 Ronny Pacheco

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Needed modules

In [2]:
import pickle
import os
import pandas as pd

In [3]:
# https://kioku-space.com/en/jupyter-skip-execution/
from IPython.core.magic import register_cell_magic # type: ignore


@register_cell_magic
def skip(line, cell):
    print('Skipping cell')
    if line and cell:
        pass
    return

# Pickle save

In [4]:
%%skip
# =============================================================================
# main function
# =============================================================================
def data_save_load(option):
    """
    This function is used to save or load data for the jupyter notebook
    """
    path_folder = "ipynb_db"  # Folder to save variables
    os.makedirs(path_folder, exist_ok=True)  # Create folder if not exist
    notebook_name = os.path.basename(os.path.abspath(''))
    path_file = os.path.join(path_folder, f"{notebook_name}.variables.pkl") # Path to save the variables

    if option == "save":
        with open(path_file, "wb") as pickle_file:
            dict_variables = {
            }
            pickle.dump(dict_variables, pickle_file)
    elif option == "load":
        with open(path_file, "rb") as pickle_file:
            variables = pickle.load(pickle_file)
        # Now load the variables
        for pickle_key, pickle_value in variables.items():
            print(f"* Loading variable: {pickle_key}")
            globals()[pickle_key] = pickle_value
# =============================================================================
# Call the function
# =============================================================================
data_save_load(option="load")

Skipping cell

# Load needed data

## Relationship in "families"

In [5]:
# Load table with relationships
rel_df = pd.read_csv("./data/negative_noCDS_relationship_named.csv", sep=',', header=None)
print(rel_df.shape)
rel_df

(456, 14)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Seq_0_LinJ.01|rejected_noCDS_c01.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Seq_1_LinJ.01|rejected_noCDS_c01.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Seq_2_LinJ.01|rejected_noCDS_c01.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Seq_3_LinJ.01|rejected_noCDS_c01.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Seq_4_LinJ.01|rejected_noCDS_c01.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,Seq_666_LinJ.36|rejected_noCDS_c36.6650CS,Seq_667_LinJ.36|rejected_noCDS_c36.6660CS,Seq_668_LinJ.36|rejected_noCDS_c36.6670CS,Seq_669_LinJ.36|rejected_noCDS_c36.6680CS,Seq_670_LinJ.36|rejected_noCDS_c36.6690CS,Seq_671_LinJ.36|rejected_noCDS_c36.6700CS,Seq_672_LinJ.36|rejected_noCDS_c36.6710CS,Seq_673_LinJ.36|rejected_noCDS_c36.6720CS,NaN,NaN,NaN,NaN,NaN,NaN
452,Seq_674_LinJ.36|rejected_noCDS_c36.6730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
453,Seq_675_LinJ.36|rejected_noCDS_c36.6740CT,Seq_678_LinJ.36|rejected_noCDS_c36.6770CT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
454,Seq_676_LinJ.36|rejected_noCDS_c36.6750CU,Seq_680_LinJ.36|rejected_noCDS_c36.6790CU,Seq_681_LinJ.36|rejected_noCDS_c36.6800CU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,Seq_677_LinJ.36|rejected_noCDS_c36.6760CV,Seq_679_LinJ.36|rejected_noCDS_c36.6780CV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Leishmania Repeated Element sequence data

In [6]:
# Load the data frame with the sequences and data from these "leishmania repeated elements"
lre_df = pd.read_csv('./data/negative_database_nomatch_corrected_named.csv', sep=',', header=0)
print(lre_df.shape)
print('='*50)
print(lre_df.dtypes)
lre_df

(682, 6)
==================================================
sseqid     object
sstart      int64
send        int64
sstrand    object
sseq       object
name       object
dtype: object

,sseqid,sstart,send,sstrand,sseq,name
0,LinJ.01,36103,36242,plus,AGACAGACCGACACACGCAGCCGTGTGATGCCGCCGCCGAGGGCAG...,rejected_noCDS_c01.10
1,LinJ.01,113760,114388,plus,CAGCGCCATGCACGACATGGCCGCTGACGTCCGTAGCCCTAACTCG...,rejected_noCDS_c01.20
2,LinJ.01,146412,146530,plus,GCGAATTGTGTTCTGCGCATGCCTCTTCTCTGCCGTGCAGCATGCG...,rejected_noCDS_c01.30
3,LinJ.01,261866,262439,plus,CGGACTTGGCAAGTGGCCGCCATCGATGAAAACGCACCATGCCTTT...,rejected_noCDS_c01.40
4,LinJ.01,271363,271650,plus,CGAACGCCGCCCTCAATCGCGCGCTGAACTTCACGCGGCGGTCGAC...,rejected_noCDS_c01.50
...,...,...,...,...,...,...
677,LinJ.36,2648605,2648838,plus,CAGGCTCCCATCACACCAGCGGCCAGTGAGGCGGCCCAAGGAGGTA...,rejected_noCDS_c36.6760CV
678,LinJ.36,2658534,2658789,plus,ATACAAAAAAAGACTGCAGTGATGGAAAGCACAGGAAGGGTGACGG...,rejected_noCDS_c36.6770CT
679,LinJ.36,2665095,2665328,plus,CAGGCTCCCATCACACCAGCGGCCAGTGAGGCGGCCCAAGGAGGTA...,rejected_noCDS_c36.6780CV
680,LinJ.36,2691919,2692135,plus,TCTGCCACAAAACACGAGCTCCACTCCACGCTACAGCCGCCCTGCC...,rejected_noCDS_c36.6790CU
681,LinJ.36,2706883,2707095,plus,TCTGCCACAAAACACGAGCTCCACTCCACGCTACAGCCGCCCTGCC...,rejected_noCDS_c36.6800CU

# Modify data

## Relationship data

In [7]:
# From "rel_df" remove all rows whose second column is "NaN"
rel_df = rel_df.dropna(subset=[1])
print(rel_df.shape)
rel_df

(100, 14)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
5,Seq_5_LinJ.01|rejected_noCDS_c01.60A,Seq_252_LinJ.22|rejected_noCDS_c22.2530A,Seq_253_LinJ.22|rejected_noCDS_c22.2540A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Seq_8_LinJ.02|rejected_noCDS_c02.90B,Seq_12_LinJ.02|rejected_noCDS_c02.130B,Seq_15_LinJ.02|rejected_noCDS_c02.160B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Seq_19_LinJ.04|rejected_noCDS_c04.200C,Seq_20_LinJ.04|rejected_noCDS_c04.210C,Seq_23_LinJ.04|rejected_noCDS_c04.240C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Seq_29_LinJ.05|rejected_noCDS_c05.300D,Seq_31_LinJ.05|rejected_noCDS_c05.320D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Seq_32_LinJ.05|rejected_noCDS_c05.330E,Seq_33_LinJ.05|rejected_noCDS_c05.340E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,Seq_655_LinJ.36|rejected_noCDS_c36.6540CR,Seq_657_LinJ.36|rejected_noCDS_c36.6560CR,Seq_659_LinJ.36|rejected_noCDS_c36.6580CR,Seq_661_LinJ.36|rejected_noCDS_c36.6600CR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,Seq_666_LinJ.36|rejected_noCDS_c36.6650CS,Seq_667_LinJ.36|rejected_noCDS_c36.6660CS,Seq_668_LinJ.36|rejected_noCDS_c36.6670CS,Seq_669_LinJ.36|rejected_noCDS_c36.6680CS,Seq_670_LinJ.36|rejected_noCDS_c36.6690CS,Seq_671_LinJ.36|rejected_noCDS_c36.6700CS,Seq_672_LinJ.36|rejected_noCDS_c36.6710CS,Seq_673_LinJ.36|rejected_noCDS_c36.6720CS,NaN,NaN,NaN,NaN,NaN,NaN
453,Seq_675_LinJ.36|rejected_noCDS_c36.6740CT,Seq_678_LinJ.36|rejected_noCDS_c36.6770CT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
454,Seq_676_LinJ.36|rejected_noCDS_c36.6750CU,Seq_680_LinJ.36|rejected_noCDS_c36.6790CU,Seq_681_LinJ.36|rejected_noCDS_c36.6800CU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,Seq_677_LinJ.36|rejected_noCDS_c36.6760CV,Seq_679_LinJ.36|rejected_noCDS_c36.6780CV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
rel_df = rel_df.copy()
for _, row in rel_df.iterrows():
    for elem in row.dropna():
        new_elem = elem.split("|")[1]
        row[row == elem] = new_elem
rel_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
5,rejected_noCDS_c01.60A,rejected_noCDS_c22.2530A,rejected_noCDS_c22.2540A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,rejected_noCDS_c02.90B,rejected_noCDS_c02.130B,rejected_noCDS_c02.160B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,rejected_noCDS_c04.200C,rejected_noCDS_c04.210C,rejected_noCDS_c04.240C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,rejected_noCDS_c05.300D,rejected_noCDS_c05.320D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,rejected_noCDS_c05.330E,rejected_noCDS_c05.340E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,rejected_noCDS_c36.6540CR,rejected_noCDS_c36.6560CR,rejected_noCDS_c36.6580CR,rejected_noCDS_c36.6600CR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,rejected_noCDS_c36.6650CS,rejected_noCDS_c36.6660CS,rejected_noCDS_c36.6670CS,rejected_noCDS_c36.6680CS,rejected_noCDS_c36.6690CS,rejected_noCDS_c36.6700CS,rejected_noCDS_c36.6710CS,rejected_noCDS_c36.6720CS,NaN,NaN,NaN,NaN,NaN,NaN
453,rejected_noCDS_c36.6740CT,rejected_noCDS_c36.6770CT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
454,rejected_noCDS_c36.6750CU,rejected_noCDS_c36.6790CU,rejected_noCDS_c36.6800CU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,rejected_noCDS_c36.6760CV,rejected_noCDS_c36.6780CV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# How many elements are there?
counter = 0
for _, row in rel_df.iterrows():
    counter += len(row.dropna())
print(f'There are {counter} elements in total.')

There are 324 elements in total.

## LRE data

In [10]:
# In "lre_df" remove all rows where the string in "name" doesn't end in a "letter"
lre_df = lre_df[lre_df['name'].str.match(r'.*[A-Za-z]$')]
print(lre_df.shape)
lre_df

(326, 6)

,sseqid,sstart,send,sstrand,sseq,name
5,LinJ.01,272907,275894,plus,CTTTCTCTGTCTTCACTTCCTCGGTGCGTCTGGTGGTGGTTGCGCC...,rejected_noCDS_c01.60A
8,LinJ.02,95421,95743,plus,TCCGCGATCCGTGCAGTTGGCGCCGGCCCCTCCTTCACTGCCGATG...,rejected_noCDS_c02.90B
12,LinJ.02,138891,139213,plus,TCCGCGATCCGTGCAGTTGGCGCCGGCCCCTCCTTCACTGCCGATG...,rejected_noCDS_c02.130B
15,LinJ.02,198554,198709,plus,TCCGCGATCCGTGCAGTTGGCGCCGGCCCCTCCTTCACTGCCGATG...,rejected_noCDS_c02.160B
19,LinJ.04,121451,121728,plus,CCCCCCCATCCCTGCCACCATTCCCCCATTGCCGAACCACCCCTCA...,rejected_noCDS_c04.200C
...,...,...,...,...,...,...
677,LinJ.36,2648605,2648838,plus,CAGGCTCCCATCACACCAGCGGCCAGTGAGGCGGCCCAAGGAGGTA...,rejected_noCDS_c36.6760CV
678,LinJ.36,2658534,2658789,plus,ATACAAAAAAAGACTGCAGTGATGGAAAGCACAGGAAGGGTGACGG...,rejected_noCDS_c36.6770CT
679,LinJ.36,2665095,2665328,plus,CAGGCTCCCATCACACCAGCGGCCAGTGAGGCGGCCCAAGGAGGTA...,rejected_noCDS_c36.6780CV
680,LinJ.36,2691919,2692135,plus,TCTGCCACAAAACACGAGCTCCACTCCACGCTACAGCCGCCCTGCC...,rejected_noCDS_c36.6790CU
681,LinJ.36,2706883,2707095,plus,TCTGCCACAAAACACGAGCTCCACTCCACGCTACAGCCGCCCTGCC...,rejected_noCDS_c36.6800CU

## Checking problem

In [11]:
# Let's check why rel_df and lre_df doesn't have the same length
names_rel = [elem for _, row in rel_df.iterrows() for elem in row.dropna()]
print(len(names_rel))
print(type(names_rel))

324
<class 'list'>

In [12]:
names_lre = lre_df['name'].tolist()
print(len(names_lre))
print(type(names_lre))

326
<class 'list'>

In [13]:
rejected_errors = []
for elem in names_lre:
    if elem not in names_rel:
        print(f"Element {elem} is not in lre_df")
        rejected_errors.append(elem)

Element rejected_noCDS_BLAST_ERROR is not in lre_df
Element rejected_noCDS_BLAST_ERROR is not in lre_df

Ok, it was because these elements were here, which were an error in BLASTn search. Where BLASTn couldn't find them

In [14]:
# Remove them
lre_df = lre_df[~lre_df['name'].isin(rejected_errors)]
print(lre_df.shape)

(324, 6)

In [15]:
# Remove unused variables
del(names_rel, names_lre, rejected_errors)

# Renaming

## rel_df

In [16]:
# Let's rename the data in "rel_df"
lre_name = 'lre'  # From 'leishmania repetitive element'
lre_group_counter = 0
for _, row in rel_df.iterrows():
    lre_group_counter += 1  # So the first group starts in 0
    lre_group_member_counter = 0
    for elem in row.dropna():
        lre_group_member_counter += 1  # So the first group member starts in 1
        old_name = elem
        new_name = f"{lre_name}_{lre_group_counter}.{lre_group_member_counter}"
        row[row==elem] = f"{old_name}|{new_name}"

# Let's check the results
rel_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
5,rejected_noCDS_c01.60A|lre_1.1,rejected_noCDS_c22.2530A|lre_1.2,rejected_noCDS_c22.2540A|lre_1.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,rejected_noCDS_c02.90B|lre_2.1,rejected_noCDS_c02.130B|lre_2.2,rejected_noCDS_c02.160B|lre_2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,rejected_noCDS_c04.200C|lre_3.1,rejected_noCDS_c04.210C|lre_3.2,rejected_noCDS_c04.240C|lre_3.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,rejected_noCDS_c05.300D|lre_4.1,rejected_noCDS_c05.320D|lre_4.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,rejected_noCDS_c05.330E|lre_5.1,rejected_noCDS_c05.340E|lre_5.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,rejected_noCDS_c36.6540CR|lre_96.1,rejected_noCDS_c36.6560CR|lre_96.2,rejected_noCDS_c36.6580CR|lre_96.3,rejected_noCDS_c36.6600CR|lre_96.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,rejected_noCDS_c36.6650CS|lre_97.1,rejected_noCDS_c36.6660CS|lre_97.2,rejected_noCDS_c36.6670CS|lre_97.3,rejected_noCDS_c36.6680CS|lre_97.4,rejected_noCDS_c36.6690CS|lre_97.5,rejected_noCDS_c36.6700CS|lre_97.6,rejected_noCDS_c36.6710CS|lre_97.7,rejected_noCDS_c36.6720CS|lre_97.8,NaN,NaN,NaN,NaN,NaN,NaN
453,rejected_noCDS_c36.6740CT|lre_98.1,rejected_noCDS_c36.6770CT|lre_98.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
454,rejected_noCDS_c36.6750CU|lre_99.1,rejected_noCDS_c36.6790CU|lre_99.2,rejected_noCDS_c36.6800CU|lre_99.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,rejected_noCDS_c36.6760CV|lre_100.1,rejected_noCDS_c36.6780CV|lre_100.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## lre_df

In [17]:
# Let's take a list from the "rel_df"
rel_names_list = [elem for _,row in rel_df.iterrows() for elem in row.dropna()]

# Let's create a dict with each element. Split by "|" and the left will be the key and the right the value:
rel_names_dict = {}
for elem in rel_names_list:
    key, value = elem.split("|")
    rel_names_dict[key] = value

In [18]:
# Now let's change the data in "lre_df" column "name". For each name found in "rel_names_dict" keys, replace it for its value
lre_df.loc[:, 'name'] = lre_df['name'].map(rel_names_dict)

In [19]:
# Check for NaN values in the 'name' column
print(f'Number of NaN values: {lre_df.loc[:, 'name'].isna().sum()}')
lre_df

Number of NaN values: 0

,sseqid,sstart,send,sstrand,sseq,name
5,LinJ.01,272907,275894,plus,CTTTCTCTGTCTTCACTTCCTCGGTGCGTCTGGTGGTGGTTGCGCC...,lre_1.1
8,LinJ.02,95421,95743,plus,TCCGCGATCCGTGCAGTTGGCGCCGGCCCCTCCTTCACTGCCGATG...,lre_2.1
12,LinJ.02,138891,139213,plus,TCCGCGATCCGTGCAGTTGGCGCCGGCCCCTCCTTCACTGCCGATG...,lre_2.2
15,LinJ.02,198554,198709,plus,TCCGCGATCCGTGCAGTTGGCGCCGGCCCCTCCTTCACTGCCGATG...,lre_2.3
19,LinJ.04,121451,121728,plus,CCCCCCCATCCCTGCCACCATTCCCCCATTGCCGAACCACCCCTCA...,lre_3.1
...,...,...,...,...,...,...
677,LinJ.36,2648605,2648838,plus,CAGGCTCCCATCACACCAGCGGCCAGTGAGGCGGCCCAAGGAGGTA...,lre_100.1
678,LinJ.36,2658534,2658789,plus,ATACAAAAAAAGACTGCAGTGATGGAAAGCACAGGAAGGGTGACGG...,lre_98.2
679,LinJ.36,2665095,2665328,plus,CAGGCTCCCATCACACCAGCGGCCAGTGAGGCGGCCCAAGGAGGTA...,lre_100.2
680,LinJ.36,2691919,2692135,plus,TCTGCCACAAAACACGAGCTCCACTCCACGCTACAGCCGCCCTGCC...,lre_99.2
681,LinJ.36,2706883,2707095,plus,TCTGCCACAAAACACGAGCTCCACTCCACGCTACAGCCGCCCTGCC...,lre_99.3

# GFF creation

In [68]:
# Columns needed for GFF file
COLUMN_NAMES = ['seqname', 'source', 'feature', 'start', 'end', 'score', 'strand', 'frame', 'attribute']

def create_gff_line(gff_row, gff_attribute_col, gff_source, gff_feature=None, gff_strand=None):
    """
    :param gff_row: Dictionary containing data for creating GFF line; keys should include 'sseqid', 'sstart', 'send', 'sstrand'
    :param gff_attribute_col: Key in gff_row to be used for GFF attribute column; if set to '.', defaults to '.'
    :param gff_source: Optional source field for GFF line; defaults to None
    :param gff_feature: Optional feature field for GFF line; defaults to None
    :param gff_strand: Optional strand field for GFF line; if not provided, defaults to '.'
    :return: Dictionary representing a GFF line with provided information
    """
    row_gff = {
        'seqname': gff_row['sseqid'],
        'source': gff_source,
        'feature': gff_feature,
        'start': gff_row['sstart'],
        'end': gff_row['send'],
        'score': '.',
        'strand': gff_row['sstrand'] if gff_strand else '.',  # Simplified condition for gff_strand
        'frame': '.',
        'attribute': f'ID={gff_row[gff_attribute_col]}' if gff_attribute_col != '.' else '.',  # Simplified condition for gff_attribute_col
    }
    
    return row_gff


def create_gff(data_frame, gff_attribute_col, gff_source, gff_feature=None, gff_strand=None):
    """
    :param data_frame: Pandas DataFrame containing the data to be converted to GFF format.
    :param gff_attribute_col: The column in the DataFrame that contains the attributes to be included in the GFF output.
    :param gff_source: The source of the GFF entries, can be None or a specific string.
    :param gff_feature: The feature type for the GFF entries, can be None or a specific string.
    :param gff_strand: The strand information for the GFF entries, can be None or a specific string.
    :return: A new Pandas DataFrame containing the formatted GFF entries.
    """
    pre_gff = [
        create_gff_line(gff_row, gff_attribute_col=gff_attribute_col, gff_source=gff_source)
        for _, gff_row in data_frame.iterrows()
    ]
    return pd.DataFrame(pre_gff, columns=COLUMN_NAMES)

# Let's save the GFF data about 'lre_gff'.
lre_gff = create_gff(lre_df, gff_source='CBM', gff_attribute_col='name')
lre_gff.head()

   seqname source feature   start     end score strand frame   attribute
0  LinJ.01    CBM    None  272907  275894     .      .     .  ID=lre_1.1
1  LinJ.02    CBM    None   95421   95743     .      .     .  ID=lre_2.1
2  LinJ.02    CBM    None  138891  139213     .      .     .  ID=lre_2.2
3  LinJ.02    CBM    None  198554  198709     .      .     .  ID=lre_2.3
4  LinJ.04    CBM    None  121451  121728     .      .     .  ID=lre_3.1

In [70]:
# Let's save the data
lre_gff.to_csv("./data_1.1/lre.gff", header=None, index=False, sep='\t')

# Save data

In [103]:
lre_df.to_csv("./data_1.1/lre_named.csv", header=True, index=False, sep=',')

In [104]:
# Modify "rel_df" so it has only the new names strucutre
for _, row in rel_df.iterrows():
    for elem in row.dropna():
        new_elem = elem.split("|")[1]
        row[row == elem] = new_elem

In [105]:
# Save the data
rel_df.to_csv("./data_1.1/relationship_named.csv", header=False, index=False, sep=',')