# Code

## Get neg_data that didn't match LmSIDER2A|B

In [57]:
# Needed modules
import pandas as pd
from Bio import SeqIO

In [6]:
# Import filtered negative data from consensus + LmSIDER2A|B data
neg_data = pd.read_csv("./data/consensus+LmSIDER2A+B/negatives_testing_elements.csv", sep=",", header=0)
print(neg_data.shape)
print(neg_data.dtypes)
neg_data.head()

(714, 5)
sseqid     object
sstart      int64
send        int64
sstrand    object
sseq       object
dtype: object

,sseqid,sstart,send,sstrand,sseq
0,LinJ.01,113760,114388,plus,CAGCGCCATGCACGACATGGCCGCTGACGTCCGTAGCCCTAACTCG...
1,LinJ.01,261866,262439,plus,CGGACTTGGCAAGTGGCCGCCATCGATGAAAACGCACCATGCCTTT...
2,LinJ.01,272496,275901,plus,GTCAGAACAACGAAGCCGCCCCCCATCACTGCCTCCCTCTACGTAC...
3,LinJ.02,95421,95743,plus,TCCGCGATCCGTGCAGTTGGCGCCGGCCCCTCCTTCACTGCCGATG...
4,LinJ.02,97368,97489,plus,TCGAGCTCAGCTCTGGGGCACGGTTTGGCGGGCGTGGAAGTGGGCC...

In [7]:
# Import matches from LmSIDER2A|B data with LmSIDER2A|B hallmarks
hallmark_matches = pd.read_csv("./data/consensus+LmSIDER2A+B/negatives_testing_elements_matches_with_LmSIDER2A+B.csv", sep=",", header=0)
print(hallmark_matches.shape)
print(hallmark_matches.dtypes)
hallmark_matches.head()

(85, 12)
qseqid       object
sseqid       object
pident      float64
length        int64
qstart        int64
qend          int64
sstart        int64
send          int64
evalue      float64
bitscore    float64
qlen          int64
slen          int64
dtype: object

,qseqid,sseqid,pident,length,qstart,qend,sstart,send,evalue,bitscore,qlen,slen
0,LmSIDER2a,Seq_646_LinJ.35,90.476,42,3,42,266,225,1.080000e-09,54.7,79,677
1,LmSIDER2a,Seq_681_LinJ.36,80.000,65,14,78,200,139,6.470000e-07,45.4,79,610
2,LmSIDER2a,Seq_294_LinJ.25,78.571,70,1,68,1,70,6.470000e-07,45.4,79,139
3,LmSIDER2a,Seq_400_LinJ.31,79.310,58,6,63,345,292,1.080000e-04,38.1,79,669
4,LmSIDER2a,Seq_340_LinJ.28,78.689,61,14,74,15,72,1.080000e-04,38.1,79,686

In [46]:
# Filter matches with evalue <= 10^-3
hallmark_matches_filtered = hallmark_matches[hallmark_matches["evalue"] <= 10**-3].sort_values(by=["evalue"]).copy()  # evalue <= 10^-3
hallmark_matches_leftovers = hallmark_matches[~hallmark_matches.index.isin(hallmark_matches_filtered.index)].copy()  # leftovers

In [52]:
hallmark_matches_filtered.head()

,qseqid,sseqid,pident,length,qstart,qend,sstart,send,evalue,bitscore,qlen,slen,index
62,LmSIDER2b,Seq_11_LinJ.02,85.714,42,1,42,345,304,6.260000e-07,45.4,77,635,11
63,LmSIDER2b,Seq_13_LinJ.03,87.179,39,1,38,44,82,2.250000e-06,43.6,77,151,13
70,LmSIDER2b,Seq_26_LinJ.04,78.689,61,17,71,61,2,1.000000e-03,34.4,77,531,26
10,LmSIDER2a,Seq_26_LinJ.04,78.125,64,16,72,172,109,1.000000e-03,34.4,79,531,26
9,LmSIDER2a,Seq_27_LinJ.04,78.125,64,16,72,33,96,1.000000e-03,34.4,79,653,27

In [51]:
hallmark_matches_leftovers.head()

,qseqid,sseqid,pident,length,qstart,qend,sstart,send,evalue,bitscore,qlen,slen,index
11,LmSIDER2a,Seq_11_LinJ.02,80.000,50,35,79,428,381,0.018,30.7,79,635,11
84,LmSIDER2b,Seq_21_LinJ.04,93.333,15,6,20,35,49,2.900,23.3,77,690,21
23,LmSIDER2a,Seq_23_LinJ.04,100.000,14,47,60,333,320,0.230,27.0,79,637,23
20,LmSIDER2a,Seq_33_LinJ.05,100.000,15,60,74,508,494,0.065,28.8,79,1000,33
19,LmSIDER2a,Seq_34_LinJ.05,94.444,18,60,77,260,243,0.065,28.8,79,689,34

In [50]:
# Get index from sseqid, set as int and sort by index
hallmark_matches_filtered["index"] = hallmark_matches_filtered["sseqid"].str.extract(r'_(\d+)_').astype(int)
hallmark_matches_filtered.sort_values(by="index", ascending=True, inplace=True)

hallmark_matches_leftovers["index"] = hallmark_matches_leftovers["sseqid"].str.extract(r'_(\d+)_').astype(int)
hallmark_matches_leftovers.sort_values(by="index", ascending=True, inplace=True)

In [61]:
# To contrast need the index from hallmark_matches_filtered
index_filtered = hallmark_matches_filtered["index"].unique().tolist()
print(len(index_filtered))
print(type(index_filtered))
print(index_filtered)

23
<class 'list'>
[11, 13, 26, 27, 28, 29, 102, 189, 190, 205, 206, 207, 211, 279, 280, 281, 294, 340, 378, 400, 646, 671, 681]

In [56]:
# Now we are interested in the hallmark_matches_leftovers index
index_leftovers = hallmark_matches_leftovers["index"].unique().tolist()
print(len(index_leftovers))
print(type(index_leftovers))
print(index_leftovers)

49
<class 'list'>
[11, 21, 23, 33, 34, 35, 50, 51, 61, 65, 68, 106, 130, 133, 136, 140, 143, 147, 149, 151, 152, 168, 189, 190, 210, 236, 238, 239, 271, 275, 276, 293, 294, 301, 302, 305, 307, 309, 328, 371, 378, 387, 560, 633, 646, 684, 709, 710, 711]

In [62]:
# Remove numbers in index_leftovers that are in index
index_leftovers = [x for x in index_leftovers if x not in index_filtered]
print(len(index_leftovers))
print(type(index_leftovers))
print(index_leftovers)

43
<class 'list'>
[21, 23, 33, 34, 35, 50, 51, 61, 65, 68, 106, 130, 133, 136, 140, 143, 147, 149, 151, 152, 168, 210, 236, 238, 239, 271, 275, 276, 293, 301, 302, 305, 307, 309, 328, 371, 387, 560, 633, 684, 709, 710, 711]

## Get the data from negatives_testing_elements.csv that is not in the hallmark_matches

In [63]:
# add index column to hallmark_matches
hallmark_matches["index"] = hallmark_matches["sseqid"].str.extract(r'_(\d+)_').astype(int)
hallmark_matches.sort_values(by="index", ascending=True, inplace=True)
print(hallmark_matches.shape)
print(hallmark_matches.dtypes)
hallmark_matches.head()

(85, 13)
qseqid       object
sseqid       object
pident      float64
length        int64
qstart        int64
qend          int64
sstart        int64
send          int64
evalue      float64
bitscore    float64
qlen          int64
slen          int64
index         int64
dtype: object

,qseqid,sseqid,pident,length,qstart,qend,sstart,send,evalue,bitscore,qlen,slen,index
11,LmSIDER2a,Seq_11_LinJ.02,80.000,50,35,79,428,381,1.800000e-02,30.7,79,635,11
62,LmSIDER2b,Seq_11_LinJ.02,85.714,42,1,42,345,304,6.260000e-07,45.4,77,635,11
63,LmSIDER2b,Seq_13_LinJ.03,87.179,39,1,38,44,82,2.250000e-06,43.6,77,151,13
84,LmSIDER2b,Seq_21_LinJ.04,93.333,15,6,20,35,49,2.900000e+00,23.3,77,690,21
23,LmSIDER2a,Seq_23_LinJ.04,100.000,14,47,60,333,320,2.300000e-01,27.0,79,637,23

In [64]:
# Get the index in a list
index_matches = hallmark_matches["index"].unique().tolist()
print(len(index_matches))
print(type(index_matches))
print(index_matches)

66
<class 'list'>
[11, 13, 21, 23, 26, 27, 28, 29, 33, 34, 35, 50, 51, 61, 65, 68, 102, 106, 130, 133, 136, 140, 143, 147, 149, 151, 152, 168, 189, 190, 205, 206, 207, 210, 211, 236, 238, 239, 271, 275, 276, 279, 280, 281, 293, 294, 301, 302, 305, 307, 309, 328, 340, 371, 378, 387, 400, 560, 633, 646, 671, 681, 684, 709, 710, 711]

In [66]:
# Define function to extract fasta sequences
def fasta_extractor(pathfile, outfile, extract_list):
    with open(outfile, "w") as out_file:
        # Remember "enumerate" starts in "1"
        for count, fasta in enumerate(SeqIO.parse(open(pathfile), "fasta"), start=0):  # from Bio import SeqIO
            # name, sequence = fasta.id, str(fasta.seq)
            if count in extract_list:
                SeqIO.write(fasta, out_file, "fasta")

def fasta_extractor_exclusive(pathfile, outfile, extract_list):
    with open(outfile, "w") as out_file:
        # Remember "enumerate" starts in "1"
        for count, fasta in enumerate(SeqIO.parse(open(pathfile), "fasta"), start=0):  # from Bio import SeqIO
            # name, sequence = fasta.id, str(fasta.seq)
            if count not in extract_list:
                SeqIO.write(fasta, out_file, "fasta")

## Get fasta

In [67]:
# Get fasta from the elements in the negatives_testing_elements.fasta that are did not match with LmSIDER2A|B hallmarks in a BLASTn
fasta_extractor_exclusive(pathfile="./data/consensus+LmSIDER2A+B/negatives_testing_elements.fasta",
                          outfile="./data/consensus+LmSIDER2A+B/neg_dat_filter_decider/contrast/neg_data_no_LmSIDER2A+B/neg_data_no_LmSIDER2A+B.fasta",
                          extract_list=index_matches)  # Will get the fasta sequences that are not in index_matches

In [68]:
# Get fasta from the elements in the negatives_testing_elements.fasta that are did not match with LmSIDER2A|B hallmarks in a BLASTn and have evalue <= 10^-3
fasta_extractor(pathfile="./data/consensus+LmSIDER2A+B/negatives_testing_elements.fasta",
                outfile="./data/consensus+LmSIDER2A+B/neg_dat_filter_decider/contrast/neg_data_no_LmSIDER2A+B_and_evalue/neg_data_no_LmSIDER2A+B_and_evalue.fasta",
                extract_list=index_leftovers)  # Will get the fasta sequences that are in index_filtered