In [6]:
import pandas as pd

In [4]:
sider_df = pd.read_csv('./data/sider_relationship.csv', sep=",", header=0)
print(sider_df.shape)
print(sider_df.dtypes)
sider_df.head()

(2117, 12)
sider_name         object
gene_name          object
gene_strand        object
transcript_name    object
transcript           bool
cds                  bool
utr3                 bool
utr5                 bool
sider_chrom        object
sider_start         int64
sider_end           int64
sider_seq          object
dtype: object

,sider_name,gene_name,gene_strand,transcript_name,transcript,cds,utr3,utr5,sider_chrom,sider_start,sider_end,sider_seq
0,sre_c01.10,intergenic,NaN,intergenic,False,False,False,False,LinJ.01,1,173,ACACCAGTACACCAGTACACCAGTACACCAGTACACCAGTACACCA...
1,sre_c01.20A,LINF_010005800,-,{'LINF_01T0005800': ['3utr']},True,False,True,False,LinJ.01,24093,24758,GGGGGAGGCGGGGGAGGCGGGGGGCACGCACCTCCATGCGTGGCAT...
2,sre_c01.30A,LINF_010006300,-,{'LINF_01T0006300': ['3utr']},True,False,True,False,LinJ.01,35371,35956,ACTCCCATCGCCTGGTGCGAAGCAGCGCAAGACACACGCGCGCTGC...
3,sre_c01.40,LINF_010006600,-,{'LINF_01T0006600': ['3utr']},True,False,True,False,LinJ.01,39790,40595,ATTCTACCGCGAGCAAGGCAGCACACAGACGCACGCACAGCCACAG...
4,sre_c01.50A,LINF_010007050,-,{'LINF_01T0007050': []},True,False,False,False,LinJ.01,54983,55547,ACTCTCATCGCCTGGTGCGAAGCAGCGCAAGACACACGCGCGCTGC...

In [7]:
subset_df = sider_df.loc[
    sider_df['gene_name'] == 'intergenic',
    ['sider_name', 'sider_chrom', 'sider_start', 'sider_end']
]
print(subset_df.shape)
print(subset_df.dtypes)
subset_df.head()

(100, 4)
sider_name     object
sider_chrom    object
sider_start     int64
sider_end       int64
dtype: object

     sider_name sider_chrom  sider_start  sider_end
0    sre_c01.10     LinJ.01            1        173
5   sre_c01.60A     LinJ.01        75929      76366
12  sre_c01.130     LinJ.01       270401     271327
32   sre_c03.30     LinJ.03       254920     255296
37   sre_c04.10     LinJ.04            1        141

In [10]:
# Create new data frame with what is needed
new_df = pd.DataFrame({
    'seqname' : subset_df['sider_chrom'],
    'source' : 'CBM',
    'feature' : 'SIDER_INTERGENIC',
    'start' : subset_df['sider_start'],
    'end' : subset_df['sider_end'],
    'score' : '.',
    'strand' : '.',
    'frame' : '.',
    'attributes' : subset_df["sider_name"]
})

# Let's add "ID=" to the 'attributes' column:
new_df['attributes'] = 'ID=' + new_df['attributes']

# Let's check the data frame
print(new_df.shape)
print(new_df.dtypes)
new_df.head()

(100, 9)
seqname       object
source        object
feature       object
start          int64
end            int64
score         object
strand        object
frame         object
attributes    object
dtype: object

,seqname,source,feature,start,end,score,strand,frame,attributes
0,LinJ.01,CBM,SIDER_INTERGENIC,1,173,.,.,.,ID=sre_c01.10
5,LinJ.01,CBM,SIDER_INTERGENIC,75929,76366,.,.,.,ID=sre_c01.60A
12,LinJ.01,CBM,SIDER_INTERGENIC,270401,271327,.,.,.,ID=sre_c01.130
32,LinJ.03,CBM,SIDER_INTERGENIC,254920,255296,.,.,.,ID=sre_c03.30
37,LinJ.04,CBM,SIDER_INTERGENIC,1,141,.,.,.,ID=sre_c04.10

In [11]:
# save the subset as a tab separated .gff file
new_df.to_csv('./data/sider_intergenic.gff', sep='\t', index=False, header=False)