In [3]:
# Import needed modules
import pandas as pd

In [4]:
# read the data
data_LmSIDERs = pd.read_csv("./data/2.SIDERs_filter/positives_testing_elements.csv", sep=",", header=None)
data_LmSIDERs.columns = ["sseqid", "length", "sstart", "send", "sstrand", "sseq"]
data_chr32 = pd.read_csv("./data/4.SIDERs_filter_32chr/positives_testing_elements.csv", sep=",", header=None)
data_chr32.columns = ["sseqid", "length", "sstart", "send", "sstrand", "sseq"]
print(f"Output from LmSIDERs row length: {data_LmSIDERs.shape[0]}\n",
      f"Output from chr 32 row length: {data_chr32.shape[0]}\n",
      f"Difference: {abs(data_LmSIDERs.shape[0] - data_chr32.shape[0])}",
      sep="")

Output from LmSIDERs row length: 2156
Output from chr 32 row length: 2184
Difference: 28

In [5]:
# Check df
data_LmSIDERs.head()

,sseqid,length,sstart,send,sstrand,sseq
0,LinJ.01,1000,1,1000,plus,ACACCAGTACACCAGTACACCAGTACACCAGTACACCAGTACACCA...
1,LinJ.01,784,24093,24876,plus,GGGGGAGGCGGGGGAGGCGGGGGGCACGCACCTCCATGCGTGGCAT...
2,LinJ.01,927,35371,36297,plus,ACTCCCATCGCCTGGTGCGAAGCAGCGCAAGACACACGCGCGCTGC...
3,LinJ.01,806,39790,40595,plus,ATTCTACCGCGAGCAAGGCAGCACACAGACGCACGCACAGCCACAG...
4,LinJ.01,927,54983,55909,plus,ACTCTCATCGCCTGGTGCGAAGCAGCGCAAGACACACGCGCGCTGC...

In [6]:
# Change "plus" fpr "-"
data_LmSIDERs["sstrand"] = data_LmSIDERs["sstrand"].replace("plus", "+", regex=True)
data_chr32["sstrand"] = data_chr32["sstrand"].replace("plus", "+", regex=True)

In [7]:
# heck df after change
data_LmSIDERs.head()

,sseqid,length,sstart,send,sstrand,sseq
0,LinJ.01,1000,1,1000,+,ACACCAGTACACCAGTACACCAGTACACCAGTACACCAGTACACCA...
1,LinJ.01,784,24093,24876,+,GGGGGAGGCGGGGGAGGCGGGGGGCACGCACCTCCATGCGTGGCAT...
2,LinJ.01,927,35371,36297,+,ACTCCCATCGCCTGGTGCGAAGCAGCGCAAGACACACGCGCGCTGC...
3,LinJ.01,806,39790,40595,+,ATTCTACCGCGAGCAAGGCAGCACACAGACGCACGCACAGCCACAG...
4,LinJ.01,927,54983,55909,+,ACTCTCATCGCCTGGTGCGAAGCAGCGCAAGACACACGCGCGCTGC...

In [8]:
GFF_data_LmSIDERs = pd.DataFrame({
    'seqname': data_LmSIDERs["sseqid"],  # assuming this is a list or series of sequence names
    'source': "CBM-302",
    'feature': "SIDER",  # Ensure this is the correct feature name
    'start': data_LmSIDERs["sstart"],
    'end': data_LmSIDERs["send"],
    'score': ".",  # Placeholder if no score data
    'strand': data_LmSIDERs["sstrand"],
    'frame': ".", # Placeholder if no frame data
    'attribute': "."
})
GFF_data_LmSIDERs.head()

   seqname   source feature  start    end score strand frame attribute
0  LinJ.01  CBM-302   SIDER      1   1000     .      +     .         .
1  LinJ.01  CBM-302   SIDER  24093  24876     .      +     .         .
2  LinJ.01  CBM-302   SIDER  35371  36297     .      +     .         .
3  LinJ.01  CBM-302   SIDER  39790  40595     .      +     .         .
4  LinJ.01  CBM-302   SIDER  54983  55909     .      +     .         .

In [9]:
GFF_data_LmSIDERs.to_csv("./gff/LmSIDERs.gff", sep="\t", header=False, index=False)

In [10]:
GFF_data_chr32 = pd.DataFrame({
    'seqname': data_chr32["sseqid"],  # assuming this is a list or series of sequence names
    'source': "CBM-302",
    'feature': "SIDER",  # Ensure this is the correct feature name
    'start': data_chr32["sstart"],
    'end': data_chr32["send"],
    'score': ".",  # Placeholder if no score data
    'strand': data_chr32["sstrand"],
    'frame': ".", # Placeholder if no frame data
    'attribute': "."
})
GFF_data_chr32.head()

   seqname   source feature  start    end score strand frame attribute
0  LinJ.01  CBM-302   SIDER      1   1000     .      +     .         .
1  LinJ.01  CBM-302   SIDER  24199  24867     .      +     .         .
2  LinJ.01  CBM-302   SIDER  35374  36299     .      +     .         .
3  LinJ.01  CBM-302   SIDER  39790  40917     .      +     .         .
4  LinJ.01  CBM-302   SIDER  54986  55911     .      +     .         .

In [11]:
GFF_data_chr32.to_csv("./gff/chr32.gff", sep="\t", header=False, index=False)